parameters:
  apiDomain: '%env(API_DOMAIN)%'
  frontDomain: '%env(FRONT_DOMAIN)%'
  jwtSecretKey: '%env(JWT_SECRET_KEY)%'
  eventsParsingIterations: '%env(EVENTS_PARSING_ITERATIONS)%'
  babtParsingIterations: '%env(BABT_PARSING_ITERATIONS)%'