parameters:
  blockchain: {
    5: {
      parser: "GethEventParser",
      apiDomain: "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161",
      startBlock: 8680377,
      apiKey: "1YHP4X7F3CG2WKMZ3MSMGTCFXITYWVV6H5",
      rpcUrl: "",
      explorerUrl: "https://goerli.etherscan.io",
      currencySymbol: "ETH",
      contractAddress: "0x661376f443f2f031f220fb6245a5a9cc8d832493",
      chainName: "Goerli Testnet"
    }
  }
  gethAddress: "http://localhost:8545/"
  signer:
    address: "0x1b94bf2967c352322c72adddfe41244ccab07d45"
    password: "12345678"